#!/usr/bin/env bash
set -e

# Get the root dotfiles folder
DFSCRIPTSDIR=$(dirname $0)
cd $DFSCRIPTSDIR/..
DOTFILESDIR=$(pwd -P)

# Include core
source core-scripts/core.sh

# Run all prerequisite scripts
run_topic_scripts $DOTFILESDIR "prerequisites.sh"

# Get OMZ and install it to oh-my-zsh-core
OMZ_ROOT=$DOTFILESDIR/oh-my-zsh-core
source script/download-omz

# Download private dotfiles repos, useful for repos that contain sensitive data
source script/download-private-repos

# Run the bootstrap script in all topic folders
run_topic_scripts $DORFILESDIR "bootstrap.sh"

# Move over to our install script
source script/install