#!/usr/bin/env bash
set -e

# Get the path to the script folder and the root dotfiles folder
DF_SCRIPTS_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd -P $(dirname "$DF_SCRIPTS_DIR") && pwd)"

# Change to the dotfiles root directory
cd $DOTFILES_DIR

# Include core
source core-scripts/core.sh

# Run all prerequisite scripts
run_topic_scripts $DOTFILES_DIR "prerequisites.sh"

# Download private dotfiles repos, useful for repos that contain sensitive data
source private/download.sh

# Run the bootstrap script in all topic folders
run_topic_scripts $DOTFILES_DIR "bootstrap.sh"

# Move over to our install script
source script/install