#!/usr/bin/env bash
set -e

# Get the path to the script folder and the root dotfiles folder
DF_SCRIPTS_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd -P $(dirname "$DF_SCRIPTS_DIR") && pwd)"

# Change to the dotfiles root directory
cd $DOTFILES_DIR

# Include core
source core-scripts/core.sh

# Run the install start hook
hook_run install_start

# Our scripts for the installer
run_topic_scripts $DOTFILES_DIR "install-env.sh" "pre-install.sh" "install.sh" "post-install.sh"

# Run the install end hook
hook_run install_end
