#!/usr/bin/env bash
set -e

# Get the root dotfiles folder
DFSCRIPTSDIR=$(dirname $0)
cd $DFSCRIPTSDIR/..
DOTFILESDIR=$(pwd -P)

# Include core
source core-scripts/core.sh

# Our scripts for the installer
run_topic_scripts $DOTFILESDIR "pre-install.sh" "install.sh" "post-install.sh"
