#!/usr/bin/env bash
set -e

# Debug mode check
[[ "$1" == "--debug" || -o xtrace ]] && DEBUG_ENABLED=1

# Get the root dotfiles folder
DFSCRIPTSDIR=$(dirname $0)
cd $DFSCRIPTSDIR/..
DOTFILESDIR=$(pwd -P)

# Which OS is this?
[[ $(uname -s) == "Darwin" ]] && export MACOS=1 && export UNIX=1
[[ $(uname -s) == "Linux" ]] && export LINUX=1 && export UNIX=1
uname -s | grep -q "_NT-" && export WINDOWS=1

# Check if script is interactive
STDIN_FILE_DESCRIPTOR="0"
[[ -t $STDIN_FILE_DESCRIPTOR ]] && export IS_INTERACTIVE=1

# Some libraries
source script/terminal
source script/utils
source script/packages
source script/sudo

# Setup debug mode
debug_setup

# Initialise the colours
init_colours

# Our scripts for the installer
SCRIPTS=(pre-install install post-install)
for SCRIPT_NAME in ${SCRIPTS[@]}; do

    # Loop through each script file
    for SCRIPT_FILE in $DOTFILESDIR/**/$SCRIPT_NAME.sh; do

        # If no valid files then skip this file
        [[ -f $SCRIPT_FILE ]] || break

        # Skip files in script/
        SCRIPT_FILE_NAME=${SCRIPT_FILE#$DOTFILESDIR/}
        echo $SCRIPT_FILE_NAME | egrep -q '^script/' && continue

        # Check if this section is being skipped via an env varaible
        is_valid_topic $SCRIPT_FILE_NAME $SCRIPT_NAME.sh || continue

        # Run the script
        source $SCRIPT_FILE

    done

done
