#!/usr/bin/env bash

# Blank variables
export IS_INTERACTIVE=0

# Checks if a command exists on system
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Checks if a function exists
func_exists() {
    [[ -n "$(LC_ALL=C type -t $1)" ]] && [[ "$(LC_ALL=C type -t $1)" = function ]]
}

# Test if the current shell is interactive (tests if STDIN is available)
is_interactive_shell() {
    STDIN_FILE_DESCRIPTOR="0"
    [[ -t $STDIN_FILE_DESCRIPTOR ]] && export IS_INTERACTIVE=1
}

# Checks if the current script is in a topic that is allowed to run
is_valid_topic() {

    # Variables
    local SCRIPT_PATH=$1
    local SCRIPT_FILE=$2
    local TOPIC_FOLDER=
    local SKIP_INSTALL_VARIABLE=

    # Add the extension to the script_file if it is not there
    SCRIPT_FILE=${SCRIPT_FILE%.sh}.sh

    # Get the topic folder from the script_path
    TOPIC_FOLDER=${SCRIPT_PATH%/$SCRIPT_FILE}
    TOPIC_FOLDER=$(echo $TOPIC_FOLDER | tr [:lower:] [:upper:])
    
    # Check if a skip variable is defined
    SKIP_INSTALL_VARIABLE=SKIP_${TOPIC_FOLDER}_INSTALL
    [[ -z ${!SKIP_INSTALL_VARIABLE} ]] && return
}